import random
from telegram import Bot
from telegram.ext import Updater, CommandHandler

# Komut işleyicisi: /soru
def soru(update, context):
    sorular = [
        "En romantik anınız nedir?",
        "Bir ilişkide en önemli özellik nedir?",
        "En unutulmaz ilk buluşmanız nasıl geçti?",
        "Birlikte yapmaktan en çok keyif aldığınız etkinlik nedir?",
        "Hayalinizdeki tatil yerini anlatır mısınız?",
        "En sevdiğiniz aşk şarkısı hangisi?",
        "Birlikte olduğunuz kişiyle gelecekle ilgili hayalleriniz nelerdir?",
        "En güzel hediye aldığınız anınızı anlatır mısınız?",
        "İlişkilerde güven neden önemlidir?",
        "En iyi flört ipucunuz nedir?"
        "Aile üyelerinle aran nasıl?",
        "Ailenle ne sıklıkla görüşüyorsun?",
        "Aşık olmak senin için ne ifade ediyor?",
        "Bir araba veya motosiklet sahibi olmayı düşünüyor musun?",
        "Bir arkadaşın hakkında neyi seviyorsun? Ne yaparsa seni mutlu eder?",
        "Bir çizgi film karakteriyle ilişki yaşayan birini yargılar mısın?",
        "Bir dil öğrenmek istesen hangisini öğrenmek isterdin? Neden?",
        "Bir dil öğrenmek isteseydin bu hangi dil olurdu?",
        "Bir film veya dizi karakteriyle kim olmak istersin?",
        "Bir filmi veya diziyi tekrar tekrar izleyebiliyor musun? Hangisi?",
        "Bir gün boyunca ne yapmak istersin?",
        "Bir gün boyunca yapabileceğin en keyifli şey nedir?",
        "Bir gün boyunca yapamayacağın şey nedir?",
        "Bir gün boyunca yapmak istediğin herhangi bir şey nedir?",
        "Bir gün içerisinde en çok ne zaman mutlu olursun?",
        "Bir gün içinde en sevdiğin yemeklerden üçünü söyler misin?",
        "Bir günün nasıl geçtiğini anlatır mısın?",
        "Bir gününün nasıl geçtiğini anlatır mısın?",
        "Bir insanın karakterinde seni en çok etkileyen özellik nedir?",
        "Bir kitap okuyor musun şu anda? Hangisi ve nasıl buluyorsun?",
        "Bir kitap önerir misin? Neden?",
        "Bir konuda gerçekten tutkulu musun? Nedir bu konu?",
        "Bir kurgusal karakterle bir gün geçirmek için kim olurdu?",
        "Bir mucit olsaydın, ne icat etmek isterdin?",
        "Bir müze açacak olsan hangi konuyu seçerdin?",
        "Bir müzik festivalinde neler giyersin?",
        "Bir öğrenme sürecinde en çok hangi yöntemi tercih edersin?",
        "Bir öğretmen senin hayatında nasıl bir rol oynadı?",
        "Bir seyahat yapma imkanın olsa, nereye gitmek isterdin?",
        "Bir süper güce sahip olabilseydin, hangisini seçerdin?",
        "Bir süper güce sahip olmak isterdin, ne olmasını isterdin?",
        "Bir süper gücün olsa ne olmasını isterdin? Neden?",
        "Bir süper güç kazansan ne yapardın?",
        "Bir şarkı sözü yazacak olsan, ne hakkında olurdu?",
        "Bir şarkı yazacak olsan hangi konu hakkında yazardın? Neden?",
        "Bir şarkıyı hangi durumlarda dinlersin?",
        "Bir şeyi değiştirebilseydin neyi değiştirirdin?",
        "Bir şeyler yaparken en çok neyden etkilenirsin? Müzik mi, sessizlik mi, doğa mı?",
        "Bir şeyleri nasıl öğreniyorsun, öğrenme stilin nedir?",
        "Bir tatil için gitmek istediğin en iyi yer neresidir?",
        "Birbirimizi daha iyi tanımak için hangi filmi izlemeliyiz?",
        "Birkaç yıl içinde yapmak istediğin en büyük hayalin nedir?",
        "Birlikte zaman geçirmek için en sevdiğin aktivite nedir?",
        "Birlikte zaman geçirmekten hoşlandığın aktiviteler nelerdir?",
        "Bugüne kadar yaptığın en cesur şey nedir?",
        "Çocukluğunda ne meslek hayal ediyordun?",
        "Daha önce bir doğal afet ile karşılaştın mı?",
        "Daha önce gitmediğin bir yerde tatil yapmak ister misin? Nereyi önerirsin?",
        "Daha önce gördüğün en ilginç doğal manzara nedir?",
        "Daha önce hiç yabancı bir ülkeye gittin mi? Nereye gittin?",
        "Daha önce yaptığın en iyi iş nedir?",
        "Dünya turuna çıksan hangi ülkeyi ilk ziyaret ederdin? Neden?",
        "Dünyada en çok görmek istediğin yer neresidir?",
        "Eğer dünyadaki herkesin zekasını bir çip ile artırabilecek olsaydın, bunu yapar mıydın?",
        "Eğer zaman yolculuğu yapabilseydin, hangi döneme gitmek isterdin?",
        "En beğendiğin kitap nedir?",
        "En çok etkilendiğin doğa harikası neydi?",
        "En çok hangi film karakterine benzemek isterdin?",
        "En çok hangi filmden etkiledin?",
        "En çok hangi hayvanı seviyorsun?",
        "En çok hangi meyveyi seversin? Neden?",
        "En çok hangi spor dalında başarılı olmayı hayal ediyorsun?",
        "En çok hangi sporla ilgileniyorsun?",
        "En çok hangi tür oyunları oynamaktan keyif alırsın?",
        "En çok hangi yemek tarzını seversin?",
        "En çok kiminle seyahat etmek isterdin?",
        "En çok ne zaman güler ve neyin sizi güldürdüğünü düşünürsün?",
        "En sevdiğin çevrimiçi oyun nedir?",
        "En sevdiğin çiçek hangisidir?",
        "En sevdiğin çikolata çeşidi hangisi?",
        "En sevdiğin çizgi film karakteri kimdir? Neden?",
        "En sevdiğin çizgi film veya animasyon karakteri kimdir?",
        "En sevdiğin çocukluk anılarından birini anlatabilir misin?",
        "En sevdiğin çocukluk masalı veya hikayesi hangisi?",
        "En sevdiğin çocukluk oyunu nedir?",
        "En sevdiğin doğa sporları nelerdir?",
        "En sevdiğin film hangisi?",
        "En sevdiğin film müziği nedir?",
        "En sevdiğin film nedir?",
        "En sevdiğin film türü nedir?",
        "En sevdiğin film veya dizi türleri nelerdir?",
        "En sevdiğin hava durumu nedir?",
        "En sevdiğin hayvan hangisi ve neden?",
        "En sevdiğin hayvan hangisi? Neden?",
        "En sevdiğin hayvan nedir?",
        "En sevdiğin hobiler nelerdir?",
        "En sevdiğin hobin ne? Neden?",
        "En sevdiğin içecek veya meyve suyu hangisi?",
        "En sevdiğin içki nedir?",
        "En sevdiğin kahve türü nedir?",
        "En sevdiğin kitap nedir?",
        "En sevdiğin kitap veya yazar kimdir?",
        "En sevdiğin kitap veya yazarlar kimlerdir?",
        "En sevdiğin kitaplar nelerdir?",
        "En sevdiğin mevsim hangisi ve neden?",
        "En sevdiğin mevsimde yapmayı sevdiğin aktiviteler nelerdir?",
        "En sevdiğin meyve/sebze nedir?",
        "En sevdiğin müze hangisidir?",
        "En sevdiğin müzik aleti hangisi?",
        "En sevdiğin müzik grubu veya sanatçı kimdir?",
        "En sevdiğin müzik tarzı hangisi?",
        "En sevdiğin müzik tarzı nedir? Hangi şarkıcıları seversin?",
        "En sevdiğin müzik türü hangisi?",
        "En sevdiğin müzik türü nedir?",
        "En sevdiğin oyun hangisi? Hangi özellikleri seni cezbeder?",
        "En sevdiğin oyun nedir?",
        "En sevdiğin oyun veya bulmaca nedir?",
        "En sevdiğin oyun veya oyuncağı hatırlıyor musun?",
        "En sevdiğin renk nedir? Hangi nesnede bu rengi görmek seni mutlu eder?",
        "En sevdiğin renk nedir? Neden?",
        "En sevdiğin renk nedir?",
        "En sevdiğin renkler hangileri ve neden?",
        "En sevdiğin sanat dalı hangisi (resim, heykel, dans, vs.)?",
        "En sevdiğin seyahat destinasyonun neresidir?",
        "En sevdiğin sosyal medya platformu nedir?",
        "En sevdiğin spor dalı hangisidir?",
        "En sevdiğin spor dalı nedir?",
        "En sevdiğin spor etkinliğine gitmek ister misin?",
        "En sevdiğin spor hangisi? Neden?",
        "En sevdiğin sporcu kimdir?",
        "En sevdiğin şarkı sözü nedir?",
        "En sevdiğin şarkıcı/grup kimdir?",
        "En sevdiğin tatil aktivitesi nedir?",
        "En sevdiğin tatil beldesi neresi?",
        "En sevdiğin tatil hangisi?",
        "En sevdiğin tatil nasıl geçer?",
        "En sevdiğin tatil nereye gitmek ve neden?",
        "En sevdiğin tatil yeri hangisi?",
        "En sevdiğin tatlı çeşidi nedir?",
        "En sevdiğin tatlı hangisi?",
        "En sevdiğin tatlı nedir? Kendin yapmayı denedin mi?",
        "En sevdiğin TV dizisi nedir?",
        "En sevdiğin yabancı film hangisi?",
        "En sevdiğin yazar/yazarlar kimlerdir?",
        "En sevdiğin yemek nedir?",
        "En sevdiğin yemek tarifi nedir?",
        "En sevdiğin yemekler veya restoranlar nelerdir?",
        "En sevdiğin yılbaşı gelenekleri nelerdir?",
        "En son izlediğin film nedir? Nasıl buldun?",
        "En son ne zaman ağladın? Neden?",
        "En son ne zaman bir şeyler öğrendin? Ne öğrendin?",
        "En son ne zaman bir şeyler öğretmeye çalıştın? Ne öğrettin?",
        "En son ne zaman kendi kendine konuştun?",
        "En son ne zaman kendine bir iyilik yaptın?",
        "En son ne zaman kendine bir şey öğrendin?",
        "En son ne zaman saçma bir korkun vardı?",
        "En son okudğun kitap neydi?",
        "Eski sevgililerine geri dönmeyi düşünür müsün?",
        "Eski sevgilinin en büyük eksikliği neydi?",
        "Evcil hayvanın var mı? Var ise hangi tür?",
        "Evcil hayvanların olmuş mu hiç? Olmadıysa neden?",
        "Evcil hayvanların var mı veya sahip olmayı düşünüyor musun?",
        "Evinde olması gereken üç temel eşya nedir?",
        "Favori mevsimin hangisi ve neden?",
        "Gece hayatın var mı?",
        "Geçmişte en keyif aldığın seyahat deneyimi nedir?",
        "Geçmişte izlediğin en iyi konser hangisiydi?",
        "Geçmişte katıldığın en ilginç etkinlik nedir?",
        "Geçmişte nelerden utanırsın?",
        "Geçmişte tanıştığın en ilginç kişi kimdi?",
        "Geçmişte yaptığın en büyük hata nedir?",
        "Geçmişte yaptığın en cesur veya heyecan verici şey neydi?",
        "Geçmişte yaptığın en unutulmaz yolculuğu anlatabilir misin?",
        "Geçmişte yaşadığın en komik anı nedir?",
        "Gelecekte hangi teknolojik icatlardan yararlanmak istersin?",
        "Gelecekte yapmak istediğin bir seyahat var mı?",
        "Gelecekteki hayatında hangi mesleği yapmayı istersin?",
        "Günlük rutinin nasıl bir şeydir?",
        "Hangi aksanı konuşmayı öğrenmek istersin?",
        "Hangi aktiviteleri yapmaktan hoşlanırsın?",
        "Hangi alanda kendini geliştirmek istersin?",
        "Hangi alışkanlıkların var?",
        "Hangi animasyon filmini izlemeyi en çok seversin?",
        "Hangi animasyon filmleri seversin?",
        "Hangi aşçının yemeklerini denemek istersin?",
        "Hangi becerileri geliştirmek istersin?",
        "Hangi becerilerin en iyisi olduğunu düşünüyorsun?",
        "Hangi beceriyi geliştirmek istersin?",
        "Hangi bilim dalı seni en çok ilgilendirir?",
        "Hangi çeşit hayvanı en seversin?",
        "Hangi çevresel sorunu çözmek istersin?",
        "Hangi çizgi film karakteri seni en çok etkiler?",
        "Hangi çizgi film karakterine benzetilirsin?",
        "Hangi çizgi roman karakteri seni en çok etkiler?",
        "Hangi deneyi yapmak istemezsin?",
        "Hangi dersleri sevmezsin?",
        "Hangi dilde bir şarkı yazmak istersin?",
        "Hangi dilde şiir yazmak istersin?",
        "Hangi dili akıcı bir şekilde konuşmak istersin?",
        "Hangi dili öğrenmek istersin?",
        "Hangi dilleri biliyorsun?",
        "Hangi dizi karakterinin hayatını yaşamak istersin?",
        "Hangi dizi veya film setinde çalışmak istersin?",
        "Hangi dizi veya filmin seni en çok etkiledi?",
        "Hangi doğa harikası seni en çok etkiler?",
        "Hangi doğa harikasını görmek istersin?",
        "Hangi doğa sporunu denemek istersin?",
        "Hangi doğal güzellikleri ziyaret etmek istersin?",
        "Hangi duygunun seni en sık rahatsız ettiğini düşünüyorsun?",
        "Hangi duyguyu en sık yaşarsın?",
        "Hangi eğitim alanında daha fazla bilgi sahibi olmak istersin?",
        "Hangi eğlence parkında zaman geçirmek istersin?",
        "Hangi emojiyi en sık kullanırsın?",
        "Hangi etkinliği daha çok seversin: konser mi yoksa festival mi?",
        "Hangi evcil hayvanın sahibi olmak istersin?",
        "Hangi evcil hayvanları seversin?",
        "Hangi felsefi düşüncenin seni en çok etkilediğini düşünüyorsun?",
        "Hangi festivalde eğlenmeyi tercih edersin?",
        "Hangi film karakteri seni en çok etkiledi?",
        "Hangi film karakteri seni en çok etkiler?",
        "Hangi film karakterine aşıksın?",
        "Hangi film karakterine en çok benzediğini düşünüyorsun?",
        "Hangi film karakterine en çok benziyorsun? Neden?",
        "Hangi film karakteriyle arkadaş olmak istersin?",
        "Hangi film seni en son ağlattı?",
        "Hangi film seni son zamanlarda etkiledi?",
        "Hangi film serisine bayılırsın?",
        "Hangi filmi defalarca izlemişsindir?",
        "Hangi filmi herkesin izlemesi gerektiğini düşünüyorsun?",
        "Hangi filmin seni en çok etkiledi?",
        "Hangi hayalini gerçekleştirmek için en çok çaba sarf ediyorsun?",
        "Hangi hayat felsefesine sahipsin?",
        "Hangi hayvan seni en çok temsil eder?",
        "Hangi hayvana benzediğini düşünürsün?",
        "Hangi hayvanı en seversin ve neden?",
        "Hangi hayvanı evcilleştirmek istersin?",
        "Hangi hayvanı seversin? Hangi özellikleri seni çeker?",
        "Hangi hayvanın gücünü elde etmek istersin?",
        "Hangi hayvanın güçlerini kazanmak istersin ve neden?",
        "Hangi hayvanın özelliklerini taşıdığını düşünüyorsun?",
        "Hangi hayvanın sıradışı özellikleri seni etkiler?",
        "Hangi hayvanın süper gücüne sahip olmak istersin?",
        "Hangi hayvanlardan korkarsın?",
        "Hangi hobilerin seni en çok mutlu eder?",
        "Hangi hobilerin var?",
        "Hangi hobilerinle en çok vakit geçirmeyi seversin?",
        "Hangi hobiye sahip olmak istersin?",
        "Hangi ilde yaşamak istersin?",
        "Hangi ilginç yeteneklere sahipsin?",
        "Hangi kahramanlık hikayesi seni en çok etkiledi?",
        "Hangi karakter özelliklerine sahip insanlarla arkadaş olmaktan hoşlanırsın?",
        "Hangi kelimeyi en çok kullanırsın?",
        "Hangi kıyafetin sana en yakıştığını düşünüyorsun?",
        "Hangi kişisel başarın seni en çok gururlandırır?",
        "Hangi kişisel gelişim kitabını okumayı planlıyorsun?",
        "Hangi kitabı birçok kez okudun?",
        "Hangi kitabı en son okudun? Nasıldı?",
        "Hangi kitabı en son okudun?",
        "Hangi kitabın seni en çok etkiledi?",
        "Hangi kitap karakteri seni en çok etkiledi?",
        "Hangi kitap karakterinin hayatını yaşamak istersin?",
        "Hangi kitap karakterinin yerinde olmak isterdin?",
        "Hangi kitaplar seni etkiledi?",
        "Hangi konuda daha fazla bilgi edinmek istersin?",
        "Hangi konuda en uzman olduğunu düşünüyorsun?",
        "Hangi konuda uzman olmak istersin?",
        "Hangi konuda uzmanlaşmak istersin ve neden?",
        "Hangi konuda uzmanlaşmak istersin?",
        "Hangi konularda fikir sahibi olmak istersin?",
        "Hangi korkuların var?",
        "Hangi korkunç deneyi denemek istemezsin?",
        "Hangi korkunç film seni en çok etkiledi?",
        "Hangi köpek cinsini daha çok seversin?",
        "Hangi kurgusal dünyada yaşamak istersin?",
        "Hangi kurgusal evrende bir maceraya çıkmak istersin?",
        "Hangi kurgusal evrende yaşamak isterdin?",
        "Hangi kurgusal karakter senin için en cazip olanıdır?",
        "Hangi kurgusal karakterin hayatını yaşamak isterdin?",
        "Hangi kurgusal karakterin kıyafetlerini giymek istersin?",
        "Hangi kurgusal karakterle en iyi arkadaş olursun?",
        "Hangi kültürü öğrenmek istersin ve neden?",
        "Hangi mesleği icra etmek istersin?",
        "Hangi meslek dalında başarılı olduğunu düşünüyorsun?",
        "Hangi meşhur kişiyle tanışmak istersin?",
        "Hangi mevsim senin favorin?",
        "Hangi mevsim senin için en güzeli?",
        "Hangi mevsimi daha çok seversin?",
        "Hangi mevsimi en çok seversin? Neden?",
        "Hangi mevsimi en çok seversin?",
        "Hangi meyveyi en çok seversin?",
        "Hangi moda akımını takip edersin?",
        "Hangi mutfak kültüründen yemekleri en çok seversin?",
        "Hangi müze veya galeriyi ziyaret etmek istersin?",
        "Hangi müze veya sanat galerisini gezmek istersin?",
        "Hangi müze veya sergiyi ziyaret etmek istersin?",
        "Hangi müzik aletini çalabiliyorsun?",
        "Hangi müzik aletini çalmak isterdin?",
        "Hangi müzik aletini çalmak istersin?",
        "Hangi müzik aletini öğrenmek istersin?",
        "Hangi müzik aletlerini çalmayı öğrenmek istersin?",
        "Hangi müzik tarzını dinlemeyi tercih edersin?",
        "Hangi müzik tarzını en çok dinlersin?",
        "Hangi müzik türlerini dinlemekten hoşlanırsın?",
        "Hangi müzik türlerini dinlemekten keyif alırsın?",
        "Hangi müzik türü seni en çok etkiliyor?",
        "Hangi müzik türünü daha çok dinlersin?",
        "Hangi müzik türünü dinlemeyi seversin? Neden?",
        "Hangi müzik türünü en çok seversin?",
        "Hangi müzik türünü en seversin?",
        "Hangi müzisyenin konserine gitmek isterdin?",
        "Hangi olay seni en çok etkiledi?",
        "Hangi otelde tatil yapmak istersin?",
        "Hangi oyun konsolunu tercih edersin?",
        "Hangi oyunları oynamaktan hoşlanırsın?",
        "Hangi öğrencilik yılların en unutulmaz anısı nedir?",
        "Hangi öğretmenin seni en çok etkiledi?",
        "Hangi özel günü kutlamayı daha çok seversin?",
        "Hangi özelliğin seni diğer insanlardan farklı kılar?",
        "Hangi özelliğin seni en özgün kılar?",
        "Hangi özelliğin senin için en önemli?",
        "Hangi özelliğinle en çok gurur duyarsın?",
        "Hangi özelliklerin seni en iyi tanımlar?",
        "Hangi renk seni en çok yansıtır?",
        "Hangi renkler seni en çok etkiler?",
        "Hangi renkleri daha çok seversin?",
        "Hangi sanat dalı seni daha çok ilgilendirir?",
        "Hangi sanat dalı seni en çok etkiler?",
        "Hangi sanat dalında kendini geliştirmek istersin?",
        "Hangi sanat dalını en çok seversin?",
        "Hangi sanat dalıyla ilgilenmek istersin?",
        "Hangi sanat eserine hayranlık duyarsın?",
        "Hangi sanat eserleri seni en çok etkiledi?",
        "Hangi sanatçı veya grup en sevdiğin?",
        "Hangi sanatçı veya müzik grubunu en çok seversin?",
        "Hangi sanatçının konserine gitmek istersin?",
        "Hangi sanatçının müziğini daha çok seversin?",
        "Hangi sanatsal etkinliklerden hoşlanırsın (müze gezmek, tiyatro izlemek vb.)?",
        "Hangi sebzeyi en çok seversin?",
        "Hangi siyasi lideri dinlemek istersin?",
        "Hangi sosyal medya fenomenini takip edersin?",
        "Hangi sosyal medya platformunda en çok zaman geçiriyorsun?",
        "Hangi sosyal medya platformunu daha çok kullanırsın?",
        "Hangi sosyal medya platformunu en çok kullanıyorsun ve neden?",
        "Hangi sosyal sorumluluk projesine katılmak istersin?",
        "Hangi sosyal sorun seni en çok rahatsız ediyor?",
        "Hangi spor dalında daha fazla başarılı olmak istersin?",
        "Hangi spor dalında profesyonel olmak istersin ve neden?",
        "Hangi spor dalında profesyonel olmak istersin?",
        "Hangi spor dalını daha fazla takip edersin?",
        "Hangi spor dalını öğrenmek istersin?",
        "Hangi spor dalını yapmaktan hoşlanırsın?",
        "Hangi spor etkinliği için seyahat edersin?",
        "Hangi spor etkinliğini canlı izlemek isterdin?",
        "Hangi spora başlamak istersin?",
        "Hangi spora ilgin var ama henüz deneyemedin?",
        "Hangi sporcuyu idol olarak görürsün?",
        "Hangi sporda daha başarılı olduğunu düşünüyorsun?",
        "Hangi sporda en iyi olduğunu düşünürsün?",
        "Hangi sporda uzmanlaşmak istersin?",
        "Hangi sporları seversin?",
        "Hangi sporları takip etmeyi veya yapmayı seversin?",
        "Hangi sporu en seversin? Hangi takımı tutarsın?",
        "Hangi sporu yapmak veya öğrenmek istersin?",
        "Hangi sporu yapmayı seversin ve neden?",
        "Hangi sporu yapmayı seversin?",
        "Hangi süper güce sahip olmak isterdin?",
        "Hangi süper güce sahip olmak istersin?",
        "Hangi süper güçlerin birleşimini istersin?",
        "Hangi süper kahramanın seni en çok etkiler?",
        "Hangi sürprizleri seversin?",
        "Hangi şarkı sözleri senin için anlamlıdır?",
        "Hangi şarkı sözü seni en çok etkiler?",
        "Hangi şarkıda kendini bulursun?",
        "Hangi şehirde doğdun ve büyüdün?",
        "Hangi şehirde doğdun?",
        "Hangi şehirde yaşamak istersin?",
        "Hangi şehirde yaşamayı hayal edersin?",
        "Hangi şehri gezmek istersin?",
        "Hangi şehrin kültürüne hayransın?",
        "Hangi şirketin CEO'su olmak istersin?",
        "Hangi takımın taraftarısın?",
        "Hangi tarihi dönemde yaşamak isterdin ve neden?",
        "Hangi tarihi dönemde yaşamak istersin?",
        "Hangi tarihi döneme gitmek isterdin?",
        "Hangi tarihi döneme gitmek istersin?",
        "Hangi tarihi döneme ilgi duyarsın?",
        "Hangi tarihi dönemi daha çok araştırmayı seversin?",
        "Hangi tarihi dönemi daha çok merak edersin?",
        "Hangi tarihi figürle konuşmak istersin?",
        "Hangi tarihi figürün hayatını merak ediyorsun?",
        "Hangi tarihi kişiliği daha çok merak edersin?",
        "Hangi tarihi kişiliği yakından tanımak istersin?",
        "Hangi tarihi kişilikle bir yemek yemek istersin?",
        "Hangi tarihi kişiyi daha çok merak edersin?",
        "Hangi tarihi olaya tanıklık etmek isterdin?",
        "Hangi tarihi olayı değiştirmek isterdin?",
        "Hangi tarihi yerleri gezmek istersin?",
        "Hangi tatil aktiviteleri seni mutlu eder?",
        "Hangi tatil aktivitesini daha çok seversin?",
        "Hangi tatil aktivitesini denemek istersin?",
        "Hangi tatil tipini tercih edersin? Deniz mi, dağ mı yoksa şehir mi?",
        "Hangi tatil türünü tercih edersin? (Deniz tatili, doğa tatili, kültür turu vb.)",
        "Hangi tür dans etmekten hoşlanırsın?",
        "Hangi tür filmleri izlemekten hoşlanırsın?",
        "Hangi tür kitapları okumaktan hoşlanırsın?",
        "Hangi tür kitapları okumaktan keyif alırsın (macera, romantik, bilim kurgu, vs.)?",
        "Hangi tür müzikleri dinlemeyi seversin?",
        "Hangi ülkede bir yıl yaşayabileceğini seçmek zorunda olsan hangisini seçerdin?",
        "Hangi ülkede yaşamak istemezsin?",
        "Hangi ülkede yaşamak istersin ve neden?",
        "Hangi ülkede yaşamak istersin?",
        "Hangi ülkeleri ziyaret ettiğinde kendini evinde gibi hissettin?",
        "Hangi ülkenin yemeklerini daha çok seversin?",
        "Hangi ülkeye gitmek için can atıyorsun?",
        "Hangi ülkeye seyahat etmek istersin?",
        "Hangi ülkeyi gezme hayalin var?",
        "Hangi ülkeyi ziyaret etmek istersin ve neden?",
        "Hangi ünlü ile bir araba yolculuğu yapmak istersin?",
        "Hangi ünlü ile birlikte bir sahne performansı yapmak istersin?",
        "Hangi ünlü ile birlikte bir tatil yapmak istersin?",
        "Hangi ünlü kişinin hayatından ilham alırsın?",
        "Hangi ünlü kişinin hayatını filme çekmek isterdin?",
        "Hangi ünlü kişiye benzetilirsin?",
        "Hangi ünlü kişiyi canlandırmak istersin?",
        "Hangi ünlü tarihi olaya tanıklık eden kişiyle tanışmak isterdin?",
        "Hangi ünlü yazarın eserlerini okumayı seversin?",
        "Hangi ünlünün hayatını okumak istersin?",
        "Hangi ünlüye benzediğin sıklıkla söylenir?",
        "Hangi ünlüyle birlikte bir yemek partisinde olmak istersin?",
        "Hangi ünlüyle tanışmak isterdin?",
        "Hangi ünlüyle tanışmak istersin?",
        "Hangi ünlüyü rol model olarak görürsün?",
        "Hangi ünlüyü tanımak istersin ama asla onunla flört etmek istemezsin?",
        "Hangi video oyunu karakteri seni en çok etkiler?",
        "Hangi yabancı dilde akıcı konuşmak istersin ve neden?",
        "Hangi yabancı dilde akıcı konuşmak istersin?",
        "Hangi yabancı dilde daha iyi konuşuyorsun?",
        "Hangi yabancı dilde daha iyi olmak istersin?",
        "Hangi yabancı dilde kendini yetkin hissediyorsun?",
        "Hangi yabancı ülkede tatil yapmak istersin?",
        "Hangi yabancı ülkeleri ziyaret ettiğini hatırlıyor musun?",
        "Hangi yaratıcı faaliyetlerde bulunmaktan hoşlanırsın?",
        "Hangi yaratıcı hobilerle ilgilenirsin?"
        "Hangi yaratıcı projelerde yer aldın?",
        "Hangi yaratıcılık becerilerine sahipsin?",
        "Hangi yazarın biyografisini okumayı tercih edersin?",
        "Hangi yazarın kitaplarını en çok seversin?",
        "Hangi yazarın tüm kitaplarını okudun?",
        "Hangi yemeği en seversin ve neden?",
        "Hangi yemeği en seversin? Kendi yapmayı denedin mi?",
        "Hangi yemeği en son yedinde ve nasıldı?",
        "Hangi yemeği yapmayı öğrenmek istersin?",
        "Hangi yemeği yeme konusunda en titizsin?",
        "Hangi yemek kültürünü daha çok seversin?",
        "Hangi yemek kültürünün en lezzetli olduğunu düşünüyorsun?",
        "Hangi yemek tarifini mükemmelleştirmek istersin?",
        "Hangi yemek tarifini öğrenmek istersin?",
        "Hangi yemek tariflerini en çok denemek istersin?",
        "Hangi yemek tarzını denemek istersin?",
        "Hangi yemek tarzını en çok seversin?",
        "Hangi yemekleri sevmediğini düşünüyorsun?",
        "Hangi yemekleri yapmakta usta olduğunu düşünüyorsun?",
        "Hangi yeteneklere veya hobilere sahip olmak istersin?",
        "Hangi yetenekleri geliştirmek istersin?",
        "Hangi yılbaşı geleneğini en çok seversin?",
        "Hangi yılın senin için özel olduğunu düşünüyorsun?",
        "Hangi yiyecekleri sevmezsin?",
        "Hangi yönlerinle kendini daha çok geliştirmek istersin?",
        "Hayalindeki iş nedir?",
        "Hayatında aldığın en iyi karar nedir?",
        "Hayatında başarı olarak gördüğün en büyük anın neydi?",
        "Hayatında bir değişiklik yapabileceğin dönem hangisi olurdu?",
        "Hayatında bir şeyleri yeniden yapabilseydin, neyi yapardın?",
        "Hayatında en büyük riski ne zaman aldın?",
        "Hayatında en çok eğlendiğin tatil yeri neresiydi?",
        "Hayatında en çok nelerden keyif alırsın?",
        "Hayatında en çok neye bağımlı olduğunu düşünüyorsun?",
        "Hayatında en çok neye şükredersin?",
        "Hayatında en çok pişman olduğun an nedir?",
        "Hayatında en fazla hangi ülkeye seyahat ettin?",
        "Hayatında gördüğün en güzel manzara neresidir?",
        "Hayatında hiç yasadığın en komik anı neydi?",
        "Hayatında izlediğin en iyi film hangisiydi? Neden?",
        "Hayatında karşılaştığın en büyük zorluğun neydi?",
        "Hayatında neler seni en çok motive eder?",
        "Hayatında öğrendiğin en önemli ders nedir?",
        "Hayatında pişmanlık duyduğun bir şey var mı?",
        "Hayatında sana en çok ilham veren insan kimdir?",
        "Hayatında yaptığın en büyük değişiklik neydi?",
        "Hayatında yaptığın en cesur şey nedir?",
        "Hayatındaki en büyük başarın nedir?",
        "Hayatındaki en büyük başarın neydi?",
        "Hayatındaki en büyük dönüm noktası nedir?",
        "Hayatındaki en büyük risk neydi?",
        "Hayatındaki en büyük zorluk nedir?",
        "Hayatındaki en unutulmaz anın nedir?",
        "Hayatındaki en zor kararın neydi ve ne yaptın?",
        "Hayatta gerçekleştirmek istediğin bir hedefin var mı?",
        "Hayatta herhangi bir şeyi değiştirebilseydin, neyi değiştirirdin?",
        "Hayatta yapmak istediğin en büyük şey nedir?",
        "Hayatta yapmak istediğin ilk şey nedir?",
        "Hayattaki en büyük hayalin nedir?",
        "Herhangi bir müzik aletini çalmayı öğrenmek ister miydin?",
        "Hiç kendi ses kaydını dinledin mi? Nasıl hissettin?",
        "Hobilerin nelerdir?",
        "İdeal bir akşam yemeği nasıl olurdu?",
        "İdeal bir gün nasıl geçer?",
        "İdeal bir hafta sonu gezisi nasıl olurdu?",
        "İdeal bir hafta sonu nasıl geçer?",
        "İdeal bir tatil nasıl olmalı?",
        "İdeal bir tatil nasıl olmalıdır?",
        "İlk defa hangi yaşta telefon aldın?",
        "İlk kez hangi yaita aşık oldun?",
        "Kaç dil konuşabiliyorsun? Hangileri?",
        "Kendine en güvendiğin konu nedir?",
        "Kendini bir karaktere benzetseydin, hangisi olurdun?",
        "Kendini daha iyi tanığını düşündüğün yönlerin nelerdir?",
        "Kendini nasıl motive edersin?",
        "Kendini tanımlaman gerektiğinde hangi kelimeyi kullanırsın?",
        "Kitap okuyor musun?",
        "Nerede bir tatil yapmak istersin?",
        "Okuduğun en iyi kitap hangisiydi?",
        "Sana en çok ne zaman gurur duyulduğunu hissettin?",
        "Sana en çok ne zamanlar enerji verir?",
        "Sana göre arkadaşlığın tanımı nedir?",
        "Sana göre en güzel şehir hangisidir?",
        "Sana göre gerçek mutluluk nedir?",
        "Sana göre insanların en çok kullandığı yalan nedir?",
        "Sana hayatında en çok ilham veren kişi kim?",
        "Sence en iyi özelliğin nedir?",
        "Sence en romantik şey nedir?",
        "Seni en çok ilgilendiren sosyal mesele nedir?",
        "Seni en çok korkutan şey nedir?",
        "Seni en çok motive eden şey nedir?",
        "Seni en çok mutlu eden şey nedir?",
        "Seni en çok ne mutlu eder?",
        "Seni en çok neyin korkutur?",
        "Seni en çok rahatsız eden davranış nedir?",
        "Seni mutlu eden en küçük şey nedir?",
        "Sevgilin olduğunda sosyal medya hesapalarında paylaşıyor musun?",
        "Yakın kız/ekrek arkadaşın var mı aynı evde kaldığın oluyor mu?",
        "Yemek yapmayı sever misin? Eğer öyleyse en sevdiğin yemeği yapar mısın?"
    ]

    # Rastgele bir soru seçin
    secilen_soru = random.choice(sorular)

    # Soruyu gönderin
    context.bot.send_message(chat_id=update.effective_chat.id, text=secilen_soru)

def main():
    # Telegram botunuzun erişim belirteci
    token = "TELEGRAM_BOT_TOKEN"

  # Botu başlatma
    bot = Bot(token=token)
    updater = Updater(bot=bot, use_context=True)
    dispatcher = updater.dispatcher

    # Komut işleyicilerini tanımlama
    soru_handler = CommandHandler('soru', soru)
    dispatcher.add_handler(soru_handler)

    # Botu çalıştırma
    updater.start_polling()
    updater.idle()

if __name__ == '__main__':
    main()